### ISSUE TITLE
This does not work with python 9. shows errror 

### ISSUE THREAD

**Issue by bjrukin** [TheLabbingProject/django_dicom#96]
Exception: Cython-generated file 'pandas\_libs/algos.c' not found.
                      Cython is required to compile pandas from a development branch.
                      Please install Cython or download a release package of pandas.
     
      pandas._libs.algos: -> [['pandas\\_libs/algos.c']]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of pandas
  Moving to d:\pagoda\tmmc\dicom\venv\lib\site-packages\pandas-1.4.1.dist-info\
   from D:\pagoda\tmmc\dicom\venv\Lib\site-packages\~andas-1.4.1.dist-info
  Moving to d:\pagoda\tmmc\dicom\venv\lib\site-packages\pandas\
   from D:\pagoda\tmmc\dicom\venv\Lib\site-packages\~andas
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pandas

**Comment by ZviBaratz** [comment]
@bjrukin Thank you for reporting. 
Unfortunately, I can't commit to a particular time frame for resolving this, as I'm currently mostly preoccupied with other projects. Pull requests are always very welcome, of course, if you have something in mind.
