### ISSUE TITLE
Could not install on windows 10

### ISSUE THREAD

**Issue by muhamedoufi** [TheLabbingProject/django_dicom#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ZviBaratz** [comment]
Hi @muhamedoufi , thank you for reporting. 
Unfortunately, the package isn't really actively maintained at the moment. I am currently traveling until Sep 6th, if you provide more information (Django version, DB, what exactly the issue is) I can try and take a look when I get back.
